<a href="https://colab.research.google.com/github/YokoSSS/ProgrammingPython/blob/%E6%95%B0%E7%90%86%E6%9C%80%E9%81%A9%E5%8C%96%E6%BC%94%E7%BF%92(20)/%E6%95%B0%E7%90%86%E6%9C%80%E9%81%A9%E5%8C%96%E6%BC%94%E7%BF%92%EF%BC%8820%EF%BC%892024%E5%89%8D%E6%9C%9F2_1_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## PuLPモジュールの読み込み

In [ ]:
!pip install matplotlib-venn
!apt-get -qq install -y libfluidsynth1
# https://pypi.python.org/pypi/pydot
!apt-get -qq install -y graphviz && pip install pydot
import pydot
!pip install cartopy
import cartopy
# Install pulp package
!pip install pulp
import pulp



E: Package 'libfluidsynth1' has no installation candidate


## 決定変数の定義

In [ ]:
x1 = pulp.LpVariable('x1', 0) # x1 >= 0
x2 = pulp.LpVariable('x2', 0) # x2 >= 0

## 問題の定義

In [ ]:
p = pulp.LpProblem('生産計画問題', sense=pulp.LpMaximize) # 目的関数を最大化
p += 2*x1 + 3*x2, '目的関数　利益見込み'
p += 2*x1 + 8*x2 <= 110, '原料制約'
p += 3*x1 + 2*x2 <= 40, '水制約'
p += x1 + 5*x2 <= 64, '機械稼働制約'
p

生産計画問題:
MAXIMIZE
2*x1 + 3*x2 + 0
SUBJECT TO
原料制約: 2 x1 + 8 x2 <= 110

水制約: 3 x1 + 2 x2 <= 40

機械稼働制約: x1 + 5 x2 <= 64

VARIABLES
x1 Continuous
x2 Continuous

## 最適解の計算と結果の読み取り

In [ ]:
result = p.solve() # 最適解を計算

In [ ]:
pulp.LpStatus[result] # 最適解が求められたか

'Optimal'

Optimalなら最適解が得られている．Infeasible（実行可能領域が空），Unbounded（目的関数をどこまでも良くできる）等の場合は最適解が得られていない．

In [ ]:
# 目的関数の最適値（生産計画問題の場合は利益の最大値）
pulp.value(p.objective)

46.153847000000006

利益の最大値は46.2万円

In [ ]:
# 最適解
for v in p.variables():
    print(f'{v} = {pulp.value(v)}')

x1 = 5.5384615
x2 = 11.692308


最適解は x1 = 5.54, x2 = 11.69，すなわちP1を5.54 kg，P2を11.69 kg生産するとき，利益は46.2万円で最大になる．